# Generated by Django 4.1.2 on 2022-10-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.PositiveIntegerField()),
                ('small', models.PositiveIntegerField()),
                ('big', models.PositiveIntegerField()),
                ('broken', models.PositiveIntegerField()),
                ('damage', models.PositiveIntegerField()),
                ('day_total', models.PositiveIntegerField()),
                ('production', models.PositiveSmallIntegerField()),
                ('delivery', models.PositiveIntegerField()),
                ('to_gate', models.PositiveIntegerField()),
                ('spoiled', models.PositiveIntegerField()),
                ('closing', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='eggs_info',
        ),
    ]
