# Generated by Django 4.1.2 on 2022-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0002_eggs_delete_eggs_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='big',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='broken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='closing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='day_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='delivery',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='normal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='production',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='small',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='spoiled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='to_gate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
