# Generated by Django 4.1.2 on 2022-11-14 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0005_alter_eggs_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 22, 8, 20, 526657), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='closing',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='day_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_birds', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField()),
                ('mortality', models.PositiveSmallIntegerField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggs.bt_lyr')),
            ],
        ),
    ]
