# Generated by Django 4.1.2 on 2022-11-14 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0006_eggs_date_time_alter_eggs_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggs',
            name='mortality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggs',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggs',
            name='total_birds',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 22, 19, 2, 103571), editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='birds',
        ),
    ]
