# Generated by Django 4.1.2 on 2022-11-15 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0008_alter_eggs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.date(2022, 11, 15), editable=False, unique=True),
        ),
    ]
