# Generated by Django 4.1.2 on 2022-11-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0010_alter_eggs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='production',
            field=models.FloatField(default=0),
        ),
    ]
