# Generated by Django 4.1.2 on 2022-11-27 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0011_alter_eggs_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='closing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateField(default=datetime.date(2022, 11, 27), unique=True),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='total_birds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
