# Generated by Django 4.1.2 on 2022-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0012_alter_eggs_closing_alter_eggs_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='closing',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='total_birds',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
