# Generated by Django 4.1.3 on 2023-01-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0013_alter_eggs_closing_alter_eggs_total_birds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateField(default=datetime.date(2023, 1, 23)),
        ),
    ]
