# Generated by Django 4.1.3 on 2023-01-24 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0015_alter_bt_lyr_batch_no_alter_bt_lyr_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 22, 4, 16, 207121)),
        ),
    ]
