# Generated by Django 4.1.3 on 2023-02-06 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0016_alter_eggs_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='chicks',
            fields=[
                ('batch_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 2, 6))),
                ('total_birds', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='layer',
            fields=[
                ('layer_no', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bt_lyr',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.bt_lyr'),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 22, 19, 1, 302884)),
        ),
        migrations.CreateModel(
            name='feed_chicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.PositiveIntegerField()),
                ('meter_reading', models.PositiveIntegerField()),
                ('used', models.IntegerField()),
                ('gram_per_bird', models.FloatField()),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.chicks')),
            ],
        ),
        migrations.CreateModel(
            name='chicks_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 2, 6))),
                ('total_birds', models.PositiveIntegerField(default=0)),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.chicks')),
            ],
        ),
        migrations.AlterField(
            model_name='bt_lyr',
            name='batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggs.chicks'),
        ),
        migrations.AlterField(
            model_name='bt_lyr',
            name='layer_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.layer'),
        ),
    ]
