# Generated by Django 4.1.3 on 2023-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0017_chicks_layer_bt_lyr_occupied_alter_eggs_batch_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggs',
            name='batch_no',
        ),
        migrations.DeleteModel(
            name='bt_lyr',
        ),
        migrations.DeleteModel(
            name='eggs',
        ),
    ]
