# Generated by Django 4.1.3 on 2023-02-11 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0018_remove_eggs_batch_no_delete_bt_lyr_delete_eggs'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 13, 11, 34, 748658, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 13, 11, 34, 746657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 13, 11, 34, 747661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='gram_per_bird',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='meter_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
