# Generated by Django 4.1.3 on 2023-02-12 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0020_alter_chicks_date_alter_chicks_data_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 13, 0, 13, 844423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 13, 0, 13, 844423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 13, 0, 13, 845423, tzinfo=datetime.timezone.utc)),
        ),
    ]
