# Generated by Django 4.1.3 on 2023-03-04 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0022_bt_lyr_alter_chicks_date_alter_chicks_data_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 504746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 503748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 503748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 505746, tzinfo=datetime.timezone.utc), unique=True),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 504746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 37, 28, 505746, tzinfo=datetime.timezone.utc)),
        ),
    ]
