# Generated by Django 4.1.3 on 2023-04-27 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0024_alter_bt_lyr_date_alter_chicks_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 635915, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30, unique=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='eggs',
            old_name='delivery_big',
            new_name='delivery',
        ),
        migrations.RemoveField(
            model_name='eggs',
            name='delivery_broken',
        ),
        migrations.RemoveField(
            model_name='eggs',
            name='delivery_normal',
        ),
        migrations.RemoveField(
            model_name='eggs',
            name='delivery_small',
        ),
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 634917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 633918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 633918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 635915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 634917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 634917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 4, 27, 5, 4, 15, 635915, tzinfo=datetime.timezone.utc))),
                ('delivery_normal', models.PositiveIntegerField(default=0)),
                ('delivery_big', models.PositiveIntegerField(default=0)),
                ('delivery_small', models.PositiveIntegerField(default=0)),
                ('delivery_broken', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.vendor')),
            ],
        ),
    ]
