# Generated by Django 4.0.1 on 2023-05-11 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0025_vendor_rename_delivery_big_eggs_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='total',
            new_name='total_delivery',
        ),
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 71047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 70047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 71047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 72044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 72044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 71047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 71047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 3, 35, 72044, tzinfo=utc)),
        ),
    ]
