# Generated by Django 4.1.3 on 2023-05-13 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eggs', '0026_rename_total_delivery_total_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 517882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 516884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 516884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 519882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 518882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 517882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 518882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 55, 11, 519882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='userRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'admin'), ('S', 'supervisor'), ('O', 'office_staff')], max_length=1)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
