# Generated by Django 4.1.3 on 2023-06-11 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0027_alter_bt_lyr_date_alter_chicks_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bt_lyr_no',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.bt_lyr'),
        ),
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 50490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 49490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 50490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 52491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 51490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 50490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 51490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 32, 45, 52491, tzinfo=datetime.timezone.utc)),
        ),
    ]
