# Generated by Django 4.0.1 on 2023-06-11 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0027_alter_bt_lyr_date_alter_chicks_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_lyr',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 674064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 673016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chicks_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 673016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 675054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 674064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feed_chicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 674064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feed_hen',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 674064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 26, 40, 675054, tzinfo=utc)),
        ),
    ]
